# Generated by Django 4.2.4 on 2023-10-15 11:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main_app', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=tinymce.models.HTMLField(max_length=550, verbose_name='Опис'),
        ),
    ]
