# Generated by Django 4.2.4 on 2023-10-15 11:59

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main_app', '0004_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=tinymce.models.HTMLField(verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Опис'),
        ),
    ]
