# Generated by Django 4.2.4 on 2023-09-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main_app', '0005_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
