# Generated by Django 4.2.4 on 2023-09-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main_app', '0005_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier_discount',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
