# Generated by Django 4.2.4 on 2023-10-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main_app', '0005_alter_product_characteristics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_to_popular',
            field=models.BooleanField(default=False, verbose_name='Додати до популярного'),
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_purchases',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість покупок товару'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
    ]
