# Generated by Django 4.2.4 on 2023-09-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main_app', '0006_alter_category_slug_alter_product_slug'),
        ('shop_main_app', '0006_alter_product_supplier_discount'),
    ]

    operations = [
    ]
