# Generated by Django 4.2.4 on 2023-11-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main_app', '0006_product_add_to_popular_product_number_of_purchases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Місто доставки'),
        ),
        migrations.AddField(
            model_name='user',
            name='warehouse',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Відділення'),
        ),
    ]
