# Generated by Django 4.2.4 on 2023-09-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main_app', '0007_merge_20230912_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='measure',
            options={'verbose_name_plural': 'Одиниця виміру'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Товари'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name_plural': 'Картинки товарів'},
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier_discount',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Знижка від постачальника'),
        ),
    ]
