# Generated by Django 4.2.4 on 2023-09-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main_app', '0008_alter_category_options_alter_measure_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='measure',
            options={'verbose_name': 'Одиниця виміру', 'verbose_name_plural': 'Одиниці виміру'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Картинка товару', 'verbose_name_plural': 'Картинки товарів'},
        ),
    ]
