# Generated by Django 4.2.4 on 2023-09-12 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main_app', '0009_alter_category_options_alter_measure_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop_main_app.product', verbose_name='Товарb'),
        ),
    ]
