# Generated by Django 4.2.4 on 2023-09-13 17:40

from django.db import migrations, models
import shop_main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main_app', '0011_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/', validators=[shop_main_app.validators.ImageValidator(700, 600)], verbose_name='Зображення'),
        ),
    ]
