# Generated by Django 4.2.4 on 2024-03-25 16:06

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main_app', '0011_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=tinymce.models.HTMLField(blank=True, max_length=160, null=True, verbose_name='Короткий опис'),
        ),
    ]
