# Generated by Django 4.2.4 on 2024-03-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main_app', '0013_alter_category_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, max_length=160, null=True, verbose_name='Короткий опис'),
        ),
    ]
