# Generated by Django 4.2.4 on 2024-03-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main_app', '0014_product_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Назва товару(meta title)'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Назва товару(meta title)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, max_length=160, null=True, verbose_name='Короткий опис(meta description)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, max_length=160, null=True, verbose_name='Короткий опис(meta description)'),
        ),
    ]
