version: '3'

networks:
  app_net:
    driver: bridge
  nginx_net:
    driver: bridge

services:
  nginx:
    restart: always
    image: nginx:1.23-alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./storage/static_prod:/app/shop_garden/storage/static_prod
      - ./storage/media_prod:/app/shop_garden/storage/media_prod
    networks:
      - nginx_net
  server:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: /app/shop_garden/docker/shop_garden/server-entrypoint.sh
    volumes:
      - ./storage/static_prod:/app/shop_garden/storage/static_prod
      - ./storage/media_prod:/app/shop_garden/storage/media_prod
    env_file:
      - ./shop_garden/.env
    networks:
      - nginx_net
      - app_net
    expose:
      - 8000
    depends_on:
      - db
  worker:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: /app/shop_garden/docker/shop_garden/worker-entrypoint.sh
    env_file:
      - ./shop_garden/.env
    volumes:
      - ./storage/static_prod:/app/shop_garden/storage/static_prod
    networks:
      - app_net
    depends_on:
      - server
      - redis
      - db
  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    networks:
      - app_net
  db:
    image: postgres:13.0-alpine
    env_file:
      - ./shop_garden/.env
    restart: unless-stopped
    networks:
      - app_net
    volumes:
      - ./storage/db_data:/var/lib/postgresql/data/
