# Generated by Django 4.2.4 on 2023-09-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField()),
                ('short_description', models.TextField(max_length=550)),
                ('email', models.EmailField(max_length=254)),
                ('phones', models.TextField()),
                ('facebook', models.CharField()),
                ('instagram', models.CharField()),
                ('viber', models.CharField()),
                ('telegram', models.CharField()),
                ('delivery_info', models.TextField()),
                ('return_conditions', models.TextField()),
            ],
        ),
    ]
