# Generated by Django 4.2.4 on 2023-10-08 17:28

from django.db import migrations, models
import shop_main_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel/', validators=[shop_main_app.validators.ImageValidator(1600, 700)])),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус активний/не активний')),
            ],
            options={
                'verbose_name': 'Банери каруселі',
                'verbose_name_plural': 'Карусель головної сторінки',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField()),
                ('short_description', models.TextField(max_length=550)),
                ('email', models.EmailField(max_length=254)),
                ('phones', models.TextField()),
                ('facebook', models.CharField(blank=True, null=True)),
                ('instagram', models.CharField(blank=True, null=True)),
                ('viber', models.CharField(blank=True, null=True)),
                ('telegram', models.CharField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Футтер',
                'verbose_name_plural': 'Налаштування освновного футтера',
            },
        ),
        migrations.CreateModel(
            name='ReturnPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_info', models.TextField(blank=True, null=True)),
                ('extra_context', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAndBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_info', models.TextField()),
                ('payments', models.TextField()),
                ('extra_context', models.TextField()),
            ],
        ),
    ]
