# Generated by Django 4.2.4 on 2023-09-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options_app', '0002_carousel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name_plural': 'Карусель головної сторінки'},
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name_plural': 'Налаштування футтера'},
        ),
    ]
