# Generated by Django 4.2.4 on 2024-01-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options_app', '0003_alter_returnpolicy_extra_context_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnpolicy',
            options={'verbose_name': 'Умови повернення', 'verbose_name_plural': 'Текст сторінки "Умови повернення"'},
        ),
        migrations.AlterModelOptions(
            name='shippingandbilling',
            options={'verbose_name': 'Оплата та доставка', 'verbose_name_plural': 'Текст сторінки "Оплата та доставка"'},
        ),
        migrations.RemoveField(
            model_name='returnpolicy',
            name='extra_context',
        ),
        migrations.RemoveField(
            model_name='shippingandbilling',
            name='extra_context',
        ),
    ]
