# Generated by Django 4.2.4 on 2023-09-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options_app', '0003_alter_carousel_options_alter_footer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Банери каруселі', 'verbose_name_plural': 'Карусель головної сторінки'},
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Футтер', 'verbose_name_plural': 'Налаштування футтера'},
        ),
    ]
