# Generated by Django 4.2.4 on 2024-01-18 12:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('options_app', '0004_alter_returnpolicy_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_side_of_page', tinymce.models.HTMLField()),
                ('right_side_of_page', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Про нас',
                'verbose_name_plural': 'Текст сторінки "Про нас"',
            },
        ),
    ]
