# Generated by Django 4.2.4 on 2023-09-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options_app', '0004_alter_carousel_options_alter_footer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Статус активний/не активний'),
        ),
    ]
