# Generated by Django 4.2.4 on 2023-09-12 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options_app', '0005_alter_carousel_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Футтер', 'verbose_name_plural': 'Налаштування освновного футтера'},
        ),
    ]
