# Generated by Django 4.2.4 on 2023-09-13 17:40

from django.db import migrations, models
import shop_main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('options_app', '0006_alter_footer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(upload_to='carousel/', validators=[shop_main_app.validators.ImageValidator(1600, 700)]),
        ),
    ]
