# Generated by Django 4.2.4 on 2024-01-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options_app', '0006_alter_aboutinfo_left_side_of_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('email', models.CharField(verbose_name='email address')),
                ('message', models.TextField(verbose_name='message')),
            ],
            options={
                'verbose_name': 'Контактна форма',
                'verbose_name_plural': 'Запити з "контактної форми"',
            },
        ),
    ]
