# Generated by Django 4.2.4 on 2023-09-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options_app', '0007_alter_carousel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_context', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAndBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_info', models.TextField()),
                ('payments', models.TextField()),
                ('extra_context', models.TextField()),
            ],
        ),
    ]
