# Generated by Django 4.2.4 on 2023-09-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options_app', '0008_returnpolicy_shippingandbilling'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnpolicy',
            name='main_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
