# Generated by Django 4.2.4 on 2024-01-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options_app', '0009_alter_contactform_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='status',
            field=models.CharField(choices=[('processed', 'PROCESSED'), ('awaits', 'AWAITS')], default='awaits', max_length=9),
        ),
    ]
