# Generated by Django 4.2.4 on 2024-03-15 16:59

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('options_app', '0013_alter_contactform_message_alter_contactform_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAtMainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Основний текст')),
            ],
            options={
                'verbose_name': 'Текст головної сторінки',
                'verbose_name_plural': 'Текст сторінки "Головна"',
            },
        ),
    ]
