# Generated by Django 4.2.4 on 2024-03-25 15:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('options_app', '0014_textatmainpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='textatmainpage',
            name='meta_description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Короткий опис'),
        ),
    ]
