# Generated by Django 4.2.4 on 2024-03-25 15:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('options_app', '0015_textatmainpage_meta_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textatmainpage',
            name='meta_description',
            field=tinymce.models.HTMLField(blank=True, max_length=160, null=True, verbose_name='Короткий опис'),
        ),
    ]
