# Generated by Django 4.2.4 on 2024-03-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options_app', '0018_aboutinfo_meta_description_aboutinfo_meta_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfo',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Назва сторінки'),
        ),
        migrations.AlterField(
            model_name='returnpolicy',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Назва сторінки'),
        ),
        migrations.AlterField(
            model_name='shippingandbilling',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Назва сторінки'),
        ),
    ]
