# Generated by Django 4.2.4 on 2024-03-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options_app', '0019_alter_aboutinfo_meta_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.CharField(max_length=60, verbose_name='API токен')),
                ('chanel_id', models.CharField(max_length=20, verbose_name='ID каналу')),
                ('is_bot_enable', models.BooleanField(default=False, verbose_name='Увімкнути бота')),
            ],
            options={
                'verbose_name': 'Телеграм бот',
                'verbose_name_plural': 'Конфігурація телеграм боту',
            },
        ),
    ]
